### ISSUE TITLE
Issue with .env

### ISSUE THREAD

**Issue by elboerse** [nuxt-community/adonuxt-template#52]
Hi there,
I am trying to start a project but getting this error, hope you can help me. Tell me if you need more infos.

C U  
thx

I created the folder adonuxt and then
cd adonuxt
npm install -g adonis-cli
cloned your adonuxt template
npm install
npm run dev

C:\xampp\htdocs\DevApps\adonuxt>npm run dev

> adonuxt@1.0.0 dev C:\xampp\htdocs\DevApps\adonuxt
> nodemon --watch app --watch bootstrap --watch config -x node server.js

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: C:\xampp\htdocs\DevApps\adonuxt\app/**/* C:\xampp\htdocs\DevApps\adonuxt\bootstrap/**/* C:\xampp\htdocs\DevApps\adonuxt\config/**/*
[nodemon] starting `node server.js`
{ Error: ENOENT: no such file or directory, open 'C:\xampp\htdocs\DevApps\adonuxt\.env'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.config (C:\xampp\htdocs\DevApps\adonuxt\node_modules\dotenv\lib\main.js:30:37)
    at new Env (C:\xampp\htdocs\DevApps\adonuxt\node_modules\adonis-framework\src\Env\index.js:30:12)
    at Object.closure (C:\xampp\htdocs\DevApps\adonuxt\node_modules\adonis-framework\providers\EnvProvider.js:17:14)
    at Object.Ioc._resolveProvider (C:\xampp\htdocs\DevApps\adonuxt\node_modules\adonis-fold\src\Ioc\index.js:124:53)
    at Object.Ioc.use (C:\xampp\htdocs\DevApps\adonuxt\node_modules\adonis-fold\src\Ioc\index.js:376:18)
    at Ioc.use (C:\xampp\htdocs\DevApps\adonuxt\node_modules\adonis-fold\src\Ioc\index.js:380:18)
    at fold.Registrar.register.then (C:\xampp\htdocs\DevApps\adonuxt\bootstrap\http.js:45:19)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\xampp\\htdocs\\DevApps\\adonuxt\\.env' }
info adonis:framework +0ms serving app on null:null
TypeError: (intermediate value).then is not a function
    at new NuxtController (C:\xampp\htdocs\DevApps\adonuxt\app\Http\Controllers\NuxtController.js:13:8)
    at Object.<anonymous> (C:\xampp\htdocs\DevApps\adonuxt\app\Http\Controllers\NuxtController.js:26:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireStack (C:\xampp\htdocs\DevApps\adonuxt\node_modules\require-stack\src\index.js:44:12)
    at Object.Ioc._autoLoad (C:\xampp\htdocs\DevApps\adonuxt\node_modules\adonis-fold\src\Ioc\index.js:178:18)
    at Ioc.use (C:\xampp\htdocs\DevApps\adonuxt\node_modules\adonis-fold\src\Ioc\index.js:378:18)
    at C:\xampp\htdocs\DevApps\adonuxt\server.js:19:3
    at fold.Registrar.register.then (C:\xampp\htdocs\DevApps\adonuxt\bootstrap\http.js:105:9)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)

**Comment by motia** [comment]
you need to create a `.env` file inside your project, run `cp .env.example .env` to do so.

https://adonisjs.com/docs/3.2/env#_the_env_file

**Comment by elboerse** [comment]
thx. that worked!

The build was finished.
But now I got another error and the startpage is a bit messed up! 

Do you have an idea??

thx again.. 


 ERROR  Failed to compile with 1 errors                                                                                                                                          22:15:50


 error  in ./resources/assets/img/logo.png

Module parse failed: C:\xampp\htdocs\DevApps\adonuxt\resources\assets\img\logo.png Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)

 @ ./~/vue-loader/lib/template-compiler?{"id":"data-v-6069531a","preserveWhitespace":false}!./~/vue-loader/lib/selector.js?type=template&index=0!./resources/layouts/error.vue 6:13-46
 @ ./resources/layouts/error.vue
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?reload=true ./.nuxt/client.js

(node:5804) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: C:\\xampp\\htdocs\\DevApps\\adonuxt\\C:\\xampp\\htdocs\\DevApps\\adonuxt\\.nuxt\\comp
onents contains invalid WIN32 path characters.
(node:5804) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: C:\\xampp\\htdocs\\DevApps\\adonuxt\\C:\\xampp\\htdocs\\DevApps\\adonuxt\\C:\\xampp\\
htdocs\\DevApps\\adonuxt\\.nuxt\\components contains invalid WIN32 path characters.

**Comment by elboerse** [comment]
hi there the problem was solved in issue 45. 

thx.
