### ISSUE TITLE
TypeError: Nuxt is not a constructor

### ISSUE THREAD

**Issue by daniel7912** [nuxt-community/adonuxt-template#57]
Hi,

I am getting the error 'TypeError: Nuxt is not a constructor' on a fresh install when running 'npm run serve:dev'. Here are the steps I took:

1. Install Adonis - _npm i -g adonis-cli_

2. Create new install - _adonis new --blueprint nuxt-community/adonuxt-template adonuxttest_

3. _cd adonuxttest_

4. _npm install_

5. _npm run serve:dev_

This is the complete terminal output:

`> adonuxt@1.0.0 serve:dev /Users/Dan/Projects/adonuxttest
> npm run dev

> adonuxt@1.0.0 dev /Users/Dan/Projects/adonuxttest
> nodemon --watch app --watch bootstrap --watch config --watch .env -x node server.js

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/Dan/Projects/adonuxttest/app/**/* /Users/Dan/Projects/adonuxttest/bootstrap/**/* /Users/Dan/Projects/adonuxttest/config/**/* .env
[nodemon] starting `node server.js`
info adonis:framework +0ms serving app on localhost:3000
TypeError: Nuxt is not a constructor
    at new NuxtController (/Users/Dan/Projects/adonuxttest/app/Http/Controllers/NuxtController.js:12:17)
    at Object.<anonymous> (/Users/Dan/Projects/adonuxttest/app/Http/Controllers/NuxtController.js:26:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireStack (/Users/Dan/Projects/adonuxttest/node_modules/require-stack/src/index.js:44:12)
    at Object.Ioc._autoLoad (/Users/Dan/Projects/adonuxttest/node_modules/adonis-fold/src/Ioc/index.js:178:18)
    at Ioc.use (/Users/Dan/Projects/adonuxttest/node_modules/adonis-fold/src/Ioc/index.js:378:18)
    at /Users/Dan/Projects/adonuxttest/server.js:19:3
    at fold.Registrar.register.then (/Users/Dan/Projects/adonuxttest/bootstrap/http.js:105:9)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)`

**Node version** - 6.11.0
**Adonis version** - 2.1.9

**Comment by mekroth** [comment]
Hi,

have the same error.

**Node version** - 8.1.2
**Adonis version** - 2.1.8

**Comment by cawa-93** [comment]
What Nuxt version?

**Comment by mekroth** [comment]
Hi...

The problem is version 1.0.0-rc3 (package.json "nuxt": "^ 1.0.0-rc3"). 
With nuxt version 1.0.0-alpha.4 everything ok

**Comment by zangpakto** [comment]
.then((nuxt) => {
 -        this.nuxt = nuxt
 -        if (config.dev) {
 -          this.nuxt.build()
 -        }
 -      }

If you remove those lines from the NuxtController hopefully it should help, I had a similar issue. At least I think what I changed was the right thing to do :)

**Comment by daniel7912** [comment]
If I remove 

`.then((nuxt) => {
this.nuxt = nuxt
if (config.dev) {
this.nuxt.build()
}
}` then I still get the same error.

If I leave this code removed and then install nuxt@1.0.0-alpha.4, the app builds. I do get another error instead now but it's related to the logo.png file.

` ERROR  Failed to compile with 1 errors                                                                                                                                   10:47:22 AM

 error  in ./resources/assets/img/logo.png

Module parse failed: /Users/Dan/Projects/adonuxttest/resources/assets/img/logo.png Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)

 @ ./~/vue-loader/lib/template-compiler?{"id":"data-v-3e04842c","hasScoped":true,"preserveWhitespace":false}!./~/vue-loader/lib/selector.js?type=template&index=0!./resources/layouts/error.vue 6:13-46
 @ ./resources/layouts/error.vue
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?reload=true ./.nuxt/client.js`

**Comment by zangpakto** [comment]
In the config nuxt file just add the loader if it is missing.

build: {
    loaders: [
      {
        test: /\.(png|jpe?g|gif|svg)$/,
        loader: 'url-loader',
        query: {
          limit: 10000, // 10KO
          name: 'img/[name].[hash].[ext]'
        }
      }
    ]
  }

**Comment by ConsoleTVs** [comment]
Same. Fresh installation.

![image](https://user-images.githubusercontent.com/6124435/28825162-6d4594fc-76c5-11e7-90d3-fa3608964e69.png)

**Comment by thanhminh6996** [comment]
I have same errors

**Comment by wongni** [comment]
Refer to the pull request here https://github.com/nuxt-community/adonuxt-template/pull/59

**Comment by thanhminh6996** [comment]
@wongni Thanks you, but i have new errors:
```
Error: Cannot find module 'es6-promise\auto' from 'C:\OpenServer\domains\face.io'
    at Function.module.exports [as sync] (C:\OpenServer\domains\face.io\node_modules\resolve\lib\sync.js:40:15)
    at r (C:\OpenServer\domains\face.io\node_modules\vue-server-renderer\build.js:7741:44)
    at Object.<anonymous> (webpack:/external "es6-promise/auto":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap b723638754f17ec59ca0:25:0)
    at Object.<anonymous> (server-bundle.js:1358:75)
    at __webpack_require__ (webpack:/webpack/bootstrap b723638754f17ec59ca0:25:0)
    at Object.<anonymous> (server-bundle.js:996:65)
    at __webpack_require__ (webpack:/webpack/bootstrap b723638754f17ec59ca0:25:0)
    at server-bundle.js:92:18
    at Object.<anonymous> (server-bundle.js:95:10)
    at evaluateModule (C:\OpenServer\domains\face.io\node_modules\vue-server-renderer\build.js:7747:21)
    at C:\OpenServer\domains\face.io\node_modules\vue-server-renderer\build.js:7805:18
    at Promise (<anonymous>)
    at C:\OpenServer\domains\face.io\node_modules\vue-server-renderer\build.js:7797:14
    at Object.renderToString (C:\OpenServer\domains\face.io\node_modules\vue-server-renderer\build.js:7951:9)
    at P (C:\OpenServer\domains\face.io\node_modules\nuxt\node_modules\pify\index.js:49:6)
```

**Comment by wongni** [comment]
Hi Thanh,

I can't find your comment in Github. Did you remove it?
