### ISSUE TITLE
TypeError: this.nuxt.build is not a function

### ISSUE THREAD

**Issue by cawa-93** [nuxt-community/adonuxt-template#62]
**nuxt@1.0.0-rc4**
```bash
$ node ./ace nuxtbuild

Building nuxt.js application...
TypeError: this.nuxt.build is not a function
    at NuxtBuild.handle (/mnt/d/Develop/fb-scaner/app/Commands/NuxtBuild.js:41:20)
    at handle.next (<anonymous>)
    at onFulfilled (/mnt/d/Develop/fb-scaner/node_modules/co/index.js:65:19)
    at /mnt/d/Develop/fb-scaner/node_modules/co/index.js:54:5
    at Promise (<anonymous>)
    at co (/mnt/d/Develop/fb-scaner/node_modules/co/index.js:50:10)
    at toPromise (/mnt/d/Develop/fb-scaner/node_modules/co/index.js:118:63)
    at next (/mnt/d/Develop/fb-scaner/node_modules/co/index.js:99:29)
    at onFulfilled (/mnt/d/Develop/fb-scaner/node_modules/co/index.js:69:7)
    at /mnt/d/Develop/fb-scaner/node_modules/co/index.js:54:5
    at Promise (<anonymous>)
    at co (/mnt/d/Develop/fb-scaner/node_modules/co/index.js:50:10)
    at NuxtBuild._commanderAction (/mnt/d/Develop/fb-scaner/node_modules/adonis-ace/src/Command/index.js:76:5)
    at Command.<anonymous> (/mnt/d/Develop/fb-scaner/node_modules/adonis-ace/src/Command/index.js:180:29)
    at Command.listener (/mnt/d/Develop/fb-scaner/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:125:13)
```

```js
// /app/Commands/NuxtBuild.js
'use strict'

const Command = use('Command')
const Config = use('Config')
const { Nuxt } = require('nuxt')

class NuxtBuild extends Command {
  /**
   * signature defines the requirements and name
   * of command.
   *
   * @return {String}
   */
  get signature () {
    return 'nuxtbuild'
  }

  /**
   * description is the little helpful information displayed
   * on the console.
   *
   * @return {String}
   */
  get description () {
    return 'Build for production the nuxt.js application.'
  }

  /**
   * handle method is invoked automatically by ace, once your
   * command has been executed.
   *
   * @param  {Object} args    [description]
   * @param  {Object} options [description]
   */
  * handle (args, options) {
    try {
      let config = Config.get('nuxt')
      config.dev = false
      this.nuxt = new Nuxt(config)
      console.log(this.nuxt)
      this.info('Building nuxt.js application...')
      yield this.nuxt.build()
    } catch (e) {
      console.error(e)
      process.exit(1)
    }
  }
}

module.exports = NuxtBuild

```

**Comment by liam-potter** [comment]
Change your nuxt constant to this: `const { Nuxt, Builder } = require('nuxt')`

Replace everything below `config.dev = false` with the following:
```
this.info('Building nuxt.js application')
this.nuxt = new Nuxt(config)
this.builder = new Builder(this.nuxt)
this.builder.build()
```

**Comment by kireerik** [comment]
related issue: #38
