### ISSUE TITLE
Error running new project

### ISSUE THREAD

**Issue by dipu-bd** [nuxt-community/adonuxt-template#76]
I tried to run a freshly created project. But this comes up:

```bash
$ npm run dev
> adonuxt@1.0.0 dev /home/dipu/projects/secret
> nodemon --watch app --watch bootstrap --watch config --watch .env -x node server.js

[nodemon] 1.12.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /home/dipu/projects/secret/app/**/* bootstrap /home/dipu/projects/secret/config/**/* .env
[nodemon] starting `node server.js`
/home/dipu/projects/secret/node_modules/@adonisjs/ignitor/src/Ignitor/index.js:307
  async _bootProviders () {
        ^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/dipu/projects/secret/node_modules/@adonisjs/ignitor/index.js:13:17)
[nodemon] app crashed - waiting for file changes before starting...
```

What is the solution? 

My system specs:
- adonis-cli = 2.1.9 
- ubuntu = 17.10
- node = v6.12.1
- npm = 3.10.10
- sqlite = 2.8.17

**Comment by Itsyuka** [comment]
Adonis requires Node v8

**Comment by dipu-bd** [comment]
Yes! In the new stable version the project runs properly. Thanks for the info
